# Generated by Django 4.2.6 on 2023-12-06 23:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut_usuario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_u', models.CharField(max_length=100)),
                ('apellido_u', models.CharField(max_length=100)),
                ('genero_u', models.CharField(max_length=10)),
                ('fecha_nac_u', models.DateField()),
                ('id_u', models.CharField(max_length=20, unique=True)),
                ('contraseña_u', models.CharField(max_length=100)),
                ('telefono_u', models.CharField(max_length=15)),
                ('ciudad_u', models.CharField(max_length=100)),
                ('tipo_usuario_u', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_groups', models.ManyToManyField(blank=True, related_name='usuarios_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_org_o', models.AutoField(primary_key=True, serialize=False)),
                ('personal_o', models.IntegerField()),
                ('mascotas_o', models.IntegerField()),
                ('ciudad_o', models.CharField(max_length=100)),
                ('calle_o', models.CharField(max_length=255)),
                ('tipo_personal_o', models.CharField(max_length=50)),
                ('tipo_mascotas_o', models.CharField(max_length=50)),
                ('n_calle_o', models.CharField(max_length=10)),
                ('cantidad_mascotas_o', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre_r', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_p', models.CharField(max_length=100)),
                ('nombre_mascota_p', models.CharField(max_length=100)),
                ('fecha_p', models.DateField()),
                ('comentario_p', models.TextField()),
                ('cantidad_p', models.IntegerField()),
                ('id_org_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascotas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_m', models.CharField(max_length=100)),
                ('raza_m', models.CharField(max_length=100)),
                ('vacuna_m', models.BooleanField(default=False)),
                ('tipo_m', models.CharField(max_length=100)),
                ('genero_m', models.CharField(max_length=10)),
                ('fecha_nac_m', models.DateField()),
                ('tamaño_m', models.CharField(max_length=20)),
                ('color_m', models.CharField(max_length=50)),
                ('comportamiento_m', models.TextField()),
                ('peso_m', models.FloatField()),
                ('especie_m', models.CharField(max_length=50)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_fotos_g', models.IntegerField()),
                ('descripcion_g', models.TextField(blank=True, null=True)),
                ('tipo_mascota_g', models.CharField(max_length=50)),
                ('perfil_g', models.BooleanField(default=False)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_mascotas_e', models.AutoField(primary_key=True, serialize=False)),
                ('vacunas_e', models.BooleanField()),
                ('tipo_vacuna_e', models.CharField(blank=True, max_length=50, null=True)),
                ('tratamiento_e', models.TextField(blank=True, null=True)),
                ('historial_medico_e', models.TextField(blank=True, null=True)),
                ('nutricion_e', models.TextField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('nombre_c', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_org_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.organizacion')),
                ('nombre_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.region')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
