# Generated by Django 4.2.6 on 2023-12-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superusuario',
            name='tipo_usuario_su',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario_u',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero_u',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1),
        ),
    ]
