# Generated by Django 4.2.6 on 2023-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_usuario_fecha_nac_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
