# Generated by Django 4.2.6 on 2023-12-29 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_usuario_fecha_nac_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac_u',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
