# Generated by Django 4.2.6 on 2023-12-30 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mascotas', '0008_remove_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superusuario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='superusuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='superusuario',
            name='username',
        ),
        migrations.AddField(
            model_name='superusuario',
            name='groups_su',
            field=models.ManyToManyField(blank=True, related_name='superusuario_related_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='superusuario',
            name='user_permissions_su',
            field=models.ManyToManyField(blank=True, related_name='superusuario_related_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='superusuario',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default='usuario', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
