# Generated by Django 4.2.6 on 2023-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mascotas', '0009_mascotaadoptada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña_u',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='usuarios_related_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuarios_related_permissions', to='auth.permission'),
        ),
    ]
