# Generated by Django 4.2.6 on 2023-12-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_alter_usuario_contraseña_u_alter_usuario_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_u',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
