# Generated by Django 4.2.6 on 2023-12-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0011_remove_superusuario_is_staff_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña_u',
            field=models.CharField(default=1312, max_length=128),
            preserve_default=False,
        ),
    ]
