# Generated by Django 4.2.6 on 2023-12-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0012_usuario_contraseña_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña_u',
        ),
    ]
