# Generated by Django 4.2.6 on 2023-12-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0013_remove_usuario_contraseña_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
