# Generated by Django 4.2.6 on 2023-12-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0014_mascota_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotaadoptada',
            name='adoptante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mascotaadoptada',
            name='adoptante_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
