# Generated by Django 4.2.6 on 2023-12-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0015_mascotaadoptada_adoptante_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='especie_m',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tipo_m',
        ),
        migrations.AddField(
            model_name='mascota',
            name='animal_m',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo'), ('Hámster', 'Hámster')], default='Perro', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero_m',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_m',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad_u',
            field=models.CharField(choices=[('Iquique', 'Iquique'), ('Alto Hospicio', 'Alto Hospicio')], max_length=100),
        ),
    ]
