# Generated by Django 4.2.6 on 2023-12-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0016_remove_mascota_especie_m_remove_mascota_tipo_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='genero_m',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=10),
        ),
    ]
