# Generated by Django 4.2.6 on 2023-12-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0022_mascotaadoptada_ciudad_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza_m',
            field=models.CharField(blank=True, choices=[], max_length=50),
        ),
    ]
