# Generated by Django 4.2.6 on 2023-12-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0024_alter_mascota_raza_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza_m',
            field=models.CharField(blank=True, choices=[], max_length=50),
        ),
    ]
