# Generated by Django 4.2.6 on 2023-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0031_alter_mascota_raza_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='animal_m',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo'), ('Hamster', 'Hamster')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_m',
            field=models.CharField(blank=True, choices=[], max_length=50),
        ),
    ]
